const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const AthleteState=require('../app/static/athlete-state.js');
function harness(fetch){
  const nodes=new Map();let n=0;
  const node=id=>{if(!nodes.has(id))nodes.set(id,{children:[],dataset:{},hidden:false,disabled:false,textContent:'',attributes:{},classList:{add(){},remove(){},toggle(){},contains(){return false;}},append(...items){this.children.push(...items);},prepend(...items){this.children.unshift(...items);},replaceChildren(...items){this.children=items;this.textContent='';},setAttribute(k,v){this.attributes[k]=v;},getAttribute(k){return this.attributes[k];},addEventListener(k,fn){this[k]=fn;},scrollIntoView(){this.scrolled=true;},pause(){this.paused=true;}});return nodes.get(id);};
  const context=vm.createContext({document:{querySelector:node,createElement:()=>node(`new${++n}`),createTextNode:text=>({textContent:text})},window:{location:{assign:href=>context.destination=href},sessionStorage:{setItem:(k,v)=>context.flash=v},setTimeout(){},clearTimeout(){}},HTMLMediaElement:{HAVE_METADATA:1},AthleteState,Intl,console,fetch});
  vm.runInContext(fs.readFileSync(require.resolve('../app/static/app.js'),'utf8').split('const path = window.location.pathname;')[0],context);vm.runInContext('showView=()=>{};',context);
  return{node,context};
}
const response=(data,status=200)=>({ok:status<400,status,json:async()=>data});
const text=node=>[node.textContent,...node.children.map(text)].join(' ');
test('actual list exposes review availability independently of analysis completion badge',async()=>{const h=harness(async()=>response({items:[{id:'a',status:'COMPLETED',exercise:'Sentadilla',repetitions_detected:1,coach_reviews:[{status:'COMPLETED'}]}]}));await h.context.setupList();assert.match(text(h.node('#analysis-list')),/Revisión disponible/);assert.match(text(h.node('#analysis-list')),/Ver revisión del coach/);});
test('coach feedback preserves all fields, prioritizes focus and next session, and seeks timestamp',()=>{
  const h=harness();const video=h.node('#annotated-video');video.readyState=1;video.duration=30;
  h.context.renderAthleteCoachFeedback({completed_coach_reviews:[{coach:{name:'Coach',specialty:'Fuerza'},main_focus:'Profundidad',next_session:'Tres series',strengths:'Control',summary:'Resumen',annotations:[{timestamp_s:8,type:'COMMENT',text:'Mira esta repetición'}]}]});
  const card=h.node('#athlete-coach-feedback').children[0];assert.equal(card.children[0].textContent,'Revisión del coach');
  const content=text(card);for(const field of ['Profundidad','Tres series','Control','Resumen'])assert.match(content,new RegExp(field));assert.ok(content.indexOf('Profundidad')<content.indexOf('Momentos y comentarios'));
  const note=card.children.find(c=>c.className==='rep');note.children.at(-1).onclick();assert.equal(video.currentTime,8);assert.equal(video.paused,true);
});
test('automatic observations and human feedback remain distinct in the actual document',()=>{const html=fs.readFileSync(require.resolve('../app/static/index.html'),'utf8');assert.match(html,/Momentos destacados · análisis automático/);assert.match(html,/No son feedback del coach/);assert.ok(html.indexOf('id="review-cta"')<html.indexOf('id="detail-completed"'));});
test('active request is visible and cannot be posted again',async()=>{let posts=0;const review={status:'PENDING',coach:{id:'c',name:'Coach'}};const h=harness(async(url,options={})=>{if(options.method){posts++;return response({});}return response(url==='/api/coaches'?{items:[{id:'c',name:'Coach'}]}:{status:'COMPLETED',coach_reviews:[review]});});await h.context.setupCoachSelection('a');assert.match(text(h.node('#selection-requests-list')),/Esperando revisión/);const button=h.node('#coach-list').children[0].children.at(-1);await button.onclick();assert.equal(button.disabled,true);assert.equal(posts,0);});
test('double click only posts once; 409 re-reads existing requests without claiming success',async()=>{let resolve,posts=0;const pending=new Promise(r=>resolve=r);let reviews=[];const h=harness(async(url,options={})=>{if(options.method){posts++;await pending;reviews=[{status:'PENDING',coach:{id:'c',name:'Coach'}}];return response({detail:'Ya existe una solicitud'},409);}return response(url==='/api/coaches'?{items:[{id:'c',name:'Coach'}]}:{status:'COMPLETED',coach_reviews:reviews});});await h.context.setupCoachSelection('a');const button=h.node('#coach-list').children[0].children.at(-1);const first=button.onclick();await button.onclick();resolve();await first;assert.equal(posts,1);assert.equal(button.disabled,true);assert.equal(h.context.destination,undefined);assert.equal(h.context.flash,undefined);assert.match(h.node('#coach-selection-status').textContent,/Ya existe/);});
test('uncertain failed POST plus failed read blocks retry and preserves error',async()=>{let posts=0,failed=false;const h=harness(async(url,options={})=>{if(options.method){posts++;failed=true;throw Error('Sin conexión');}if(failed)throw Error('offline');return response(url==='/api/coaches'?{items:[{id:'c',name:'Coach'}]}:{status:'COMPLETED',coach_reviews:[]});});await h.context.setupCoachSelection('a');const button=h.node('#coach-list').children[0].children.at(-1);await button.onclick();await button.onclick();assert.equal(posts,1);assert.equal(button.disabled,true);assert.match(text(h.node('#coach-selection-status')),/Sin conexión.*comprobar/);assert.equal(h.context.flash,undefined);});
test('result refresh does not reload the same video or duplicate repetitions',()=>{const h=harness();let loads=0;for(const id of ['#annotated-video','#original-video']){const video=h.node(id);Object.defineProperty(video,'src',{set(value){video.attributes.src=value;loads++;}});}const item={original_video_url:'/original',annotated_video_url:'/annotated',repetitions_detected:1,analysis_json:{},repetitions:[{number:1,start_s:0,bottom_s:2,end_s:4,metrics:{}}]};h.context.renderCompleted(item);h.context.renderCompleted(item);assert.equal(loads,2);assert.equal(h.node('#reps').children.length,1);});
