"""f1_persistence"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_f1_persistence'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('demo_key', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ATHLETE', 'COACH')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demo_key'),
    sa.UniqueConstraint('id', 'role', name='uq_users_id_role')
    )
    op.create_table('athletes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='ATHLETE', nullable=False),
    sa.CheckConstraint("role = 'ATHLETE'", name='ck_athletes_role'),
    sa.ForeignKeyConstraint(['user_id', 'role'], ['users.id', 'users.role'], name='fk_athletes_user_role'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('coaches',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='COACH', nullable=False),
    sa.Column('specialty', sa.String(length=80), nullable=False),
    sa.CheckConstraint("role = 'COACH'", name='ck_coaches_role'),
    sa.ForeignKeyConstraint(['user_id', 'role'], ['users.id', 'users.role'], name='fk_coaches_user_role'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PROCESSING', nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('video_path', sa.Text(), nullable=False),
    sa.Column('annotated_video_path', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status != 'COMPLETED' OR (result IS NOT NULL AND annotated_video_path IS NOT NULL AND completed_at IS NOT NULL)", name='ck_analyses_completed'),
    sa.CheckConstraint("status != 'FAILED' OR error IS NOT NULL", name='ck_analyses_failed'),
    sa.CheckConstraint("status IN ('PROCESSING', 'COMPLETED', 'FAILED')", name='ck_analyses_status'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_athlete_id'), 'analyses', ['athlete_id'], unique=False)
    op.create_table('ai_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp_s', sa.Float(), nullable=True),
    sa.CheckConstraint("timestamp_s >= 0 AND timestamp_s < 'Infinity'::float8", name='ck_ai_observations_timestamp'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'analysis_id', name='uq_ai_observations_analysis')
    )
    op.create_index(op.f('ix_ai_observations_analysis_id'), 'ai_observations', ['analysis_id'], unique=False)
    op.create_table('repetitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('bottom_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("start_s >= 0 AND bottom_s >= start_s AND end_s >= bottom_s AND end_s < 'Infinity'::float8", name='ck_repetitions_times'),
    sa.CheckConstraint('number > 0', name='ck_repetitions_number'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'number', name='uq_repetitions_number'),
    sa.UniqueConstraint('id', 'analysis_id', name='uq_repetitions_analysis')
    )
    op.create_index(op.f('ix_repetitions_analysis_id'), 'repetitions', ['analysis_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='REQUESTED', nullable=False),
    sa.Column('best_repetition_id', sa.Uuid(), nullable=True),
    sa.Column('work_repetition_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status != 'COMPLETED' OR (summary IS NOT NULL AND length(trim(summary)) > 0 AND completed_at IS NOT NULL)", name='ck_reviews_completed'),
    sa.CheckConstraint("status IN ('REQUESTED', 'IN_PROGRESS', 'COMPLETED')", name='ck_reviews_status'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['best_repetition_id', 'analysis_id'], ['repetitions.id', 'repetitions.analysis_id'], name='fk_reviews_best_rep'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.user_id'], ),
    sa.ForeignKeyConstraint(['work_repetition_id', 'analysis_id'], ['repetitions.id', 'repetitions.analysis_id'], name='fk_reviews_work_rep'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'analysis_id', name='uq_reviews_analysis')
    )
    op.create_index(op.f('ix_reviews_analysis_id'), 'reviews', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_reviews_coach_id'), 'reviews', ['coach_id'], unique=False)
    op.create_table('ai_observation_decisions',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.CheckConstraint("decision IN ('CONFIRMED', 'DISMISSED')", name='ck_decisions_value'),
    sa.ForeignKeyConstraint(['observation_id', 'analysis_id'], ['ai_observations.id', 'ai_observations.analysis_id'], name='fk_decisions_observation'),
    sa.ForeignKeyConstraint(['review_id', 'analysis_id'], ['reviews.id', 'reviews.analysis_id'], name='fk_decisions_review'),
    sa.PrimaryKeyConstraint('review_id', 'observation_id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp_s', sa.Float(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("timestamp_s >= 0 AND timestamp_s < 'Infinity'::float8", name='ck_annotations_timestamp'),
    sa.CheckConstraint('length(trim(body)) > 0', name='ck_annotations_body'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_review_id'), 'annotations', ['review_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_review_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_table('ai_observation_decisions')
    op.drop_index(op.f('ix_reviews_coach_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_analysis_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_repetitions_analysis_id'), table_name='repetitions')
    op.drop_table('repetitions')
    op.drop_index(op.f('ix_ai_observations_analysis_id'), table_name='ai_observations')
    op.drop_table('ai_observations')
    op.drop_index(op.f('ix_analyses_athlete_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('coaches')
    op.drop_table('athletes')
    op.drop_table('users')
    # ### end Alembic commands ###
